In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
df = sns.load_dataset("tips")

In [2]:
data_table = pd.crosstab(df['sex'], df['smoker'])

In [3]:
data_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [4]:
### Chi square table
## Observe value and expected value
observed_values = data_table.values

In [14]:
## 1st approach >> allowing chi square itself some expected value
stats_test, p, dof, expected_values = stats.chi2_contingency(observed_values)

In [15]:
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

chi_statistics = ((onserved - expected)**2) / expected

In [16]:
for i in zip(observed_values, expected_values):
    print(i)

(array([60, 97]), array([59.84016393, 97.15983607]))
(array([33, 54]), array([33.15983607, 53.84016393]))


In [17]:
chi_square_test = sum((observed - expected)**2 / expected for observed, expected in zip(observed_values, expected_values))
    

In [18]:
chi_square_stats = chi_square_test[0] + chi_square_test[1]

In [19]:
chi_square_stats

0.001934818536627623

In [20]:
dof

1

In [21]:
alpha = 0.05
chi_square_critical = stats.chi2.ppf(1-alpha, df= dof)

In [22]:
chi_square_critical

3.841458820694124

In [23]:
if chi_square_stats > chi_square_critical:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Fail to reject the null hypothesis


In [24]:
p_value = 1 - stats.chi2.cdf(x= chi_square_stats, df= dof)

In [25]:
p_value

0.964915107315732

In [26]:
if p_value <= alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Fail to reject the null hypothesis


In [27]:
### Direct / another approach
# No of hours studies daily in a weekly basis

expected_data = np.array([8,5,6,8,5,7,6])
observed_data = np.array([7,4,7,9,4,8,6])

[sum(expected_data), sum(observed_data)]

[45, 45]

In [29]:
chi_square_stats, p_value = stats.chisquare(observed_data, expected_data)

In [32]:
dof = len(observed_data) - 1
alpha = 0.05

chi_critical = stats.chi2.ppf(1-alpha, dof)

In [33]:
chi_critical

12.591587243743977

In [34]:
if chi_square_stats > chi_critical:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Fail to reject the null hypothesis
